[book]
title = "BevyðŸ’‹Godot"
authors = ["Maybee Rezbit"]
language = "en"

[output.html]
additional-css = ["AdditionalThemes.css"]
additional-js = ["AdditionalCode.js"]
default-theme = "pinkrose"
preferred-dark-theme = "pinkrose"